---

- hosts: devel-lxd01
  gather_facts: no
  become: yes
  vars_files:
    - /etc/ansible/roles/1-pre_jitsi/vars/main.yml                #lxc
    - /etc/ansible/roles/1-pre_jitsi/defaults/main.yml            #lxc
    - /etc/ansible/roles/2-Jitsi/defaults/main.yml                #jitsi
    - /etc/ansible/roles/2-Jitsi/vars/main.yml                    #jitsi
    - /etc/ansible/roles/3-post_jitsi/defaults/main.yml           #haproxy
    - /etc/ansible/roles/3-post_jitsi/vars/main.yml               #haproxy

  roles:
  - role: "/etc/ansible/roles/1-pre_jitsi"

- hosts: Jitsi
  gather_facts: yes
  roles:
    - role: "/etc/ansible/roles/2-Jitsi"
    - role: "/etc/ansible/roles/3-post_jitsi"